import './globals.css'
import Provider from './providers'

export const metadata = {
  title: 'SpaceX',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='dark'>
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
